### ISSUE TITLE
Variable length evaluation

### ISSUE THREAD

**Issue by dalision** [Yuanshi9815/LiteFocus#1]
Great work! As mentioned in the paper, the experiment is evaluated on AudioCaps, where all the clips in AudioCaps are 10 seconds long. So I wonder how the authors compared generated audios in variable lengths (10s, 20s, 80s) with the reference audio of 10s. Perhaps they just used the embedding distance and didn't consider the original length? I am looking forward to your reply.

**Comment by Yuanshi9815** [comment]
Indeed! I’m glad you noticed this. We did encounter the issue of differing audio lengths during the evaluation process. 

After reviewing the experimental code, I recalled that when we evaluated audios longer than 10 seconds, we used two approaches:

* **Method 1**: Randomly sampling a 10-second audio clip from the longer audio to compute the metrics. 
* **Method 2**: Using either the first or last 10 seconds of the audio clip for evaluation.

In our experiments, both evaluation methods yielded similar results. And we reported the results of **Method 1** in the paper.

**Comment by dalision** [comment]
Thanks for your quick response! It helps a lot.



---Original---
From: "Shi ***@***.***&gt;
Date: Fri, Sep 6, 2024 19:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Yuanshi9815/LiteFocus] Variable length evaluation (Issue #1)




 
Indeed! I’m glad you noticed this. We did encounter the issue of differing audio lengths during the evaluation process.
 
After reviewing the experimental code, I recalled that when we evaluated audios longer than 10 seconds, we used two approaches:
  
Method 1: Randomly sampling a 10-second audio clip from the longer audio to compute the metrics.
 
Method 2: Using either the first or last 10 seconds of the audio clip for evaluation.
  
In our experiments, both evaluation methods yielded similar results. And we reported the results of Method 1 in the paper.
